import { DatabaseManager } from './modules/core/database.js';
import { EmbeddingService } from './modules/core/embeddings.js';
import { LLMService } from './modules/core/llm.js';
import { StateManager } from './modules/core/state.js';
import { Scanner } from './modules/scanner/index.js';
import { QuizLogger } from './modules/quiz/logger.js';
import { QuizEngine } from './modules/quiz/engine.js';
import { Generator } from './modules/quiz/generator.js';
import { GapAnalyzer } from './modules/analytics/gapAnalyzer.js';
import { ExampleRecommender } from './modules/analytics/recommender.js';
import { Dashboard } from './modules/analytics/dashboard.js';
import { ExampleCreator } from './modules/generator/exampleCreator.js';
import { MenuSystem } from './modules/ui/menu.js';
import { SearchService } from './modules/search/service.js';

console.log('✅ All modules imported successfully!');
console.log('\n📋 Module list verified:');
console.log('  1. DatabaseManager');
console.log('  2. EmbeddingService');
console.log('  3. LLMService');
console.log('  4. StateManager');
console.log('  5. Scanner');
console.log('  6. QuizLogger');
console.log('  7. QuizEngine');
console.log('  8. Generator');
console.log('  9. GapAnalyzer');
console.log(' 10. ExampleRecommender');
console.log(' 11. Dashboard');
console.log(' 12. ExampleCreator');
console.log(' 13. MenuSystem');
console.log(' 14. SearchService');
console.log('\n🎉 System is complete and ready!');
